//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUSA.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUSA.API.ErrMessages", typeof(ErrMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GON&apos;s NO is not available to approve..
        /// </summary>
        internal static string GON_Not_Available {
            get {
                return ResourceManager.GetString("GON_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRN No&apos;s are not available to acknowledge..
        /// </summary>
        internal static string GRN_Not_Available {
            get {
                return ResourceManager.GetString("GRN_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or Refresh token..
        /// </summary>
        internal static string Invalid_Token {
            get {
                return ResourceManager.GetString("Invalid_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice amount and receipt amount are not the same..
        /// </summary>
        internal static string Invoice_Receipt_AmountNotSame {
            get {
                return ResourceManager.GetString("Invoice_Receipt_AmountNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate services..
        /// </summary>
        internal static string Service_Duplicate {
            get {
                return ResourceManager.GetString("Service_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not staff..
        /// </summary>
        internal static string User_Not_Staff {
            get {
                return ResourceManager.GetString("User_Not_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not staff, or you do not have a location..
        /// </summary>
        internal static string User_NotHave_StafforLocation {
            get {
                return ResourceManager.GetString("User_NotHave_StafforLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Access Token..
        /// </summary>
        internal static string User_Toekn_Invalid {
            get {
                return ResourceManager.GetString("User_Toekn_Invalid", resourceCulture);
            }
        }
    }
}
