// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUSA.Data;

namespace TUSA.API.Migrations
{
    [DbContext(typeof(TUSAContext))]
    [Migration("20211116155407_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TUSA.Domain.Entities.Privileges.role_master", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("role_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("role_id");

                    b.ToTable("role_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.business_unit_master", b =>
                {
                    b.Property<int>("business_unit_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("business_unit_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("business_unit_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("business_unit_id");

                    b.ToTable("business_unit_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.continent_master", b =>
                {
                    b.Property<string>("continent_code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("continent_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("continent_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("continent_code");

                    b.ToTable("continent_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.country_master", b =>
                {
                    b.Property<string>("country_code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("continent_code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("continent_mastercontinent_code")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("country_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("hvec_flag")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("country_code");

                    b.HasIndex("continent_mastercontinent_code");

                    b.ToTable("country_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.currency_conversion", b =>
                {
                    b.Property<int>("exchange_rate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("from_currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("is_active")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("to_currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("exchange_rate_id");

                    b.ToTable("currency_conversion");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.currency_master", b =>
                {
                    b.Property<string>("currency_code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("country_code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("country_mastercountry_code")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("currency_desc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("currency_symbol")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("currency_code");

                    b.HasIndex("country_mastercountry_code");

                    b.ToTable("currency_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.dynamic_form_data", b =>
                {
                    b.Property<int>("module_id")
                        .HasColumnType("int");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.Property<int>("Record_id")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("filed_value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("form_name")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("module_id", "field_id", "Record_id");

                    b.ToTable("dynamic_form_data");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.field_master", b =>
                {
                    b.Property<int>("field_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("field_data_type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("field_length")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("field_title")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("is_active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("is_dropdown")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ref_filed_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("reference_if_dropdown")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("field_id");

                    b.ToTable("field_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.form_field_matrix", b =>
                {
                    b.Property<int>("module_id")
                        .HasColumnType("int");

                    b.Property<string>("form_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("field_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comments_available")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("field_comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("field_design_type")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("field_order")
                        .HasColumnType("int");

                    b.Property<string>("field_validation")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("is_active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("nullable")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("module_id", "form_name", "field_id");

                    b.ToTable("form_field_matrix");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.forms_master", b =>
                {
                    b.Property<int>("form_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("form_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("form_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("is_active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("module_id")
                        .HasColumnType("int");

                    b.Property<int?>("module_mastermodule_id")
                        .HasColumnType("int");

                    b.HasKey("form_id");

                    b.HasIndex("module_mastermodule_id");

                    b.ToTable("forms_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.group_form_access_matrix", b =>
                {
                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.Property<int>("form_id")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("is_active")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("group_id", "form_id");

                    b.ToTable("group_form_access_matrix");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.group_master", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("display_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("group_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("group_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("group_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("group_type_id1")
                        .HasColumnType("int");

                    b.Property<string>("is_active")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("is_deleted")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("organization_name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("group_id");

                    b.HasIndex("group_type_id1");

                    b.ToTable("group_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.group_type_master", b =>
                {
                    b.Property<int>("group_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("group_type_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("group_type_id");

                    b.ToTable("group_type_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.module_master", b =>
                {
                    b.Property<int>("module_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("module_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("module_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("module_id");

                    b.ToTable("module_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.name_value_pair", b =>
                {
                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("field_id")
                        .HasColumnType("int");

                    b.Property<int?>("field_masterfield_id")
                        .HasColumnType("int");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("field_masterfield_id");

                    b.ToTable("name_value_pair");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_category_master", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("category_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.HasKey("category_id");

                    b.ToTable("pdc_category_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_element_master", b =>
                {
                    b.Property<int>("element_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("element_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("element_order_no")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pdc_category_mastercategory_id")
                        .HasColumnType("int");

                    b.Property<string>("phase")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("service_or_equipment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("units")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("element_id");

                    b.HasIndex("pdc_category_mastercategory_id");

                    b.ToTable("pdc_element_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_form_category_matrix", b =>
                {
                    b.Property<int>("matrix_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("caotegory_order_no")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("form_id")
                        .HasColumnType("int");

                    b.Property<int?>("forms_masterform_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pdc_category_mastercategory_id")
                        .HasColumnType("int");

                    b.HasKey("matrix_id");

                    b.HasIndex("forms_masterform_id");

                    b.HasIndex("pdc_category_mastercategory_id");

                    b.ToTable("pdc_form_category_matrix");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_header_data", b =>
                {
                    b.Property<int>("header_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("cod")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("currency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("form_id")
                        .HasColumnType("int");

                    b.Property<int?>("forms_masterform_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("guaranteed_availability")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("guaranteed_perf_ratio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("installed_capacity_ac")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("installed_capacity_dc")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("minimum_perf_ratio")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("project_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("project_year")
                        .HasColumnType("int");

                    b.Property<string>("supplier_group")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("total_project_cost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("year_1_onm_price")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("year_1_yield")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("year_2_onm_price")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("header_Id");

                    b.HasIndex("forms_masterform_id");

                    b.ToTable("pdc_header_data");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_project_element_data", b =>
                {
                    b.Property<int>("header_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("elementelement_id")
                        .HasColumnType("int");

                    b.Property<string>("modal_type")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pdc_header_dataheader_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("scope_commmentary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("share_in_total")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("total_service_hours")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("unit_cost")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("header_Id");

                    b.HasIndex("pdc_header_dataheader_Id");

                    b.ToTable("pdc_project_element_data");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pending_groups", b =>
                {
                    b.Property<int>("pending_group_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contact_First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("email_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("group_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_activated")
                        .HasColumnType("bit");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("organization_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pending_group_ID");

                    b.ToTable("pending_groups");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pending_groups_mails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("mail_sendedat")
                        .HasColumnType("datetime2");

                    b.Property<bool>("mail_status")
                        .HasColumnType("bit");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pending_Groupspending_group_ID")
                        .HasColumnType("int");

                    b.Property<int>("pending_group_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("pending_Groupspending_group_ID");

                    b.ToTable("pending_groups_mails");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.project_master", b =>
                {
                    b.Property<int>("project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("business_unit_id")
                        .HasColumnType("int");

                    b.Property<int?>("business_unit_id1")
                        .HasColumnType("int");

                    b.Property<string>("country_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_mastercountry_code")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("currency_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency_mastercurrency_code")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("project_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("project_end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("project_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("project_scope_id")
                        .HasColumnType("int");

                    b.Property<int?>("project_scope_id1")
                        .HasColumnType("int");

                    b.Property<string>("project_size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("project_start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("project_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("project_type_id1")
                        .HasColumnType("int");

                    b.Property<int>("project_year")
                        .HasColumnType("int");

                    b.Property<int?>("site_id")
                        .HasColumnType("int");

                    b.HasKey("project_id");

                    b.HasIndex("business_unit_id1");

                    b.HasIndex("country_mastercountry_code");

                    b.HasIndex("currency_mastercurrency_code");

                    b.HasIndex("project_scope_id1");

                    b.HasIndex("project_type_id1");

                    b.HasIndex("site_id");

                    b.ToTable("project_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.project_phase_master", b =>
                {
                    b.Property<int>("project_phase_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("project_phase_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("project_phase_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("project_phase_id");

                    b.ToTable("project_phase_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.project_scope_master", b =>
                {
                    b.Property<int>("project_scope_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("project_scope_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("project_scope_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("project_scope_id");

                    b.ToTable("project_scope_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.project_type_master", b =>
                {
                    b.Property<int>("project_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("project_type_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("project_type_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("project_type_id");

                    b.ToTable("project_type_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.quick_access_screens", b =>
                {
                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("form_id")
                        .HasColumnType("int");

                    b.Property<int>("form_list_order")
                        .HasColumnType("int");

                    b.Property<int?>("forms_masterform_id")
                        .HasColumnType("int");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_email_id")
                        .HasColumnType("int");

                    b.Property<string>("user_masteruser_email_id")
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("forms_masterform_id");

                    b.HasIndex("user_masteruser_email_id");

                    b.ToTable("quick_access_screens");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.recently_accessed_screens", b =>
                {
                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("form_id")
                        .HasColumnType("int");

                    b.Property<int>("form_list_order")
                        .HasColumnType("int");

                    b.Property<int?>("forms_masterform_id")
                        .HasColumnType("int");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_email_id")
                        .HasColumnType("int");

                    b.Property<string>("user_masteruser_email_id")
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("forms_masterform_id");

                    b.HasIndex("user_masteruser_email_id");

                    b.ToTable("recently_accessed_screens");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.site_master", b =>
                {
                    b.Property<int>("site_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country_code")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("country_mastercountry_code")
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("langitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("latitude")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("site_desc")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("site_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("site_id");

                    b.HasIndex("country_mastercountry_code");

                    b.ToTable("site_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_group_metrix", b =>
                {
                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.Property<int?>("group_mastergroup_id")
                        .HasColumnType("int");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<int?>("role_masterrole_id")
                        .HasColumnType("int");

                    b.Property<int>("user_email_id")
                        .HasColumnType("int");

                    b.Property<string>("user_masteruser_email_id")
                        .HasColumnType("nvarchar(128)");

                    b.HasIndex("group_mastergroup_id");

                    b.HasIndex("role_masterrole_id");

                    b.HasIndex("user_masteruser_email_id");

                    b.ToTable("user_group_metrix");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_fail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("loginat")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_email_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_masteruser_email_id")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("id");

                    b.HasIndex("user_masteruser_email_id");

                    b.ToTable("user_login_fail");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("loginat")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_email_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_masteruser_email_id")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("user_masteruser_email_id");

                    b.ToTable("user_login_log");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_master", b =>
                {
                    b.Property<string>("user_email_id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("activation_code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("contact_number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("is_activated")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("is_active")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("is_deleted")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("last_login_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("last_reset_attempt_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("password_changed_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("refresh_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("refresh_token_expiryat")
                        .HasColumnType("datetime2");

                    b.Property<string>("reset_password_date")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("user_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("user_type_masteruser_type_id")
                        .HasColumnType("int");

                    b.HasKey("user_email_id");

                    b.HasIndex("user_type_masteruser_type_id");

                    b.ToTable("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_type_master", b =>
                {
                    b.Property<int>("user_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("created_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("modified_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_type_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("user_type_id");

                    b.ToTable("user_type_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.country_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.continent_master", "continent_master")
                        .WithMany()
                        .HasForeignKey("continent_mastercontinent_code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("continent_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.currency_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.country_master", "country_master")
                        .WithMany()
                        .HasForeignKey("country_mastercountry_code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("country_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.forms_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.module_master", "module_master")
                        .WithMany()
                        .HasForeignKey("module_mastermodule_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("module_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.group_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.group_type_master", "group_type")
                        .WithMany()
                        .HasForeignKey("group_type_id1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("group_type");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.name_value_pair", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.field_master", "field_master")
                        .WithMany()
                        .HasForeignKey("field_masterfield_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("field_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_element_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.pdc_category_master", "pdc_category_master")
                        .WithMany()
                        .HasForeignKey("pdc_category_mastercategory_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("pdc_category_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_form_category_matrix", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.forms_master", "forms_master")
                        .WithMany()
                        .HasForeignKey("forms_masterform_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.pdc_category_master", "pdc_category_master")
                        .WithMany()
                        .HasForeignKey("pdc_category_mastercategory_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("forms_master");

                    b.Navigation("pdc_category_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_header_data", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.forms_master", "forms_master")
                        .WithMany()
                        .HasForeignKey("forms_masterform_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("forms_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pdc_project_element_data", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.pdc_header_data", "pdc_header_data")
                        .WithMany()
                        .HasForeignKey("pdc_header_dataheader_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("pdc_header_data");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.pending_groups_mails", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.pending_groups", "pending_Groups")
                        .WithMany()
                        .HasForeignKey("pending_Groupspending_group_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("pending_Groups");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.project_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.business_unit_master", "business_unit")
                        .WithMany()
                        .HasForeignKey("business_unit_id1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.country_master", "country_master")
                        .WithMany()
                        .HasForeignKey("country_mastercountry_code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.currency_master", "currency_master")
                        .WithMany()
                        .HasForeignKey("currency_mastercurrency_code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.project_scope_master", "project_scope")
                        .WithMany()
                        .HasForeignKey("project_scope_id1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.project_type_master", "project_type")
                        .WithMany()
                        .HasForeignKey("project_type_id1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.site_master", "site")
                        .WithMany()
                        .HasForeignKey("site_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("business_unit");

                    b.Navigation("country_master");

                    b.Navigation("currency_master");

                    b.Navigation("project_scope");

                    b.Navigation("project_type");

                    b.Navigation("site");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.quick_access_screens", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.forms_master", "forms_master")
                        .WithMany()
                        .HasForeignKey("forms_masterform_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.user_master", "user_master")
                        .WithMany()
                        .HasForeignKey("user_masteruser_email_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("forms_master");

                    b.Navigation("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.recently_accessed_screens", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.forms_master", "forms_master")
                        .WithMany()
                        .HasForeignKey("forms_masterform_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.user_master", "user_master")
                        .WithMany()
                        .HasForeignKey("user_masteruser_email_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("forms_master");

                    b.Navigation("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.site_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.country_master", "country_master")
                        .WithMany()
                        .HasForeignKey("country_mastercountry_code")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("country_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_group_metrix", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.group_master", "group_master")
                        .WithMany()
                        .HasForeignKey("group_mastergroup_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.Privileges.role_master", "role_master")
                        .WithMany()
                        .HasForeignKey("role_masterrole_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TUSA.Domain.Entities.user_master", "user_master")
                        .WithMany()
                        .HasForeignKey("user_masteruser_email_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("group_master");

                    b.Navigation("role_master");

                    b.Navigation("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_fail", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.user_master", "user_master")
                        .WithMany()
                        .HasForeignKey("user_masteruser_email_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_log", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.user_master", "user_master")
                        .WithMany()
                        .HasForeignKey("user_masteruser_email_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.user_type_master", "user_type_master")
                        .WithMany()
                        .HasForeignKey("user_type_masteruser_type_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user_type_master");
                });
#pragma warning restore 612, 618
        }
    }
}
