// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUSA.Data;

namespace TUSA.API.Migrations
{
    [DbContext(typeof(TUSAContext))]
    [Migration("20211019143408_updates")]
    partial class updates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TUSA.Domain.Entities.Privileges.role_master", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("role_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("role_id");

                    b.ToTable("role_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.UserMaster.user_master", b =>
                {
                    b.Property<string>("user_name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("activation_code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("contact_number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email_address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("first_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("is_activated")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("is_active")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("is_deleted")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("last_login_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("last_reset_attempt_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("password_changed_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("refresh_token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("refresh_token_expiryat")
                        .HasColumnType("datetime2");

                    b.Property<string>("reset_password_date")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("user_type_id")
                        .HasColumnType("int");

                    b.Property<int?>("user_type_id1")
                        .HasColumnType("int");

                    b.HasKey("user_name");

                    b.HasIndex("user_type_id1");

                    b.ToTable("user_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.UserMaster.user_type_master", b =>
                {
                    b.Property<int>("user_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("modified_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_type_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("user_type_id");

                    b.ToTable("user_type_master");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_fail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("loginat")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("user_login_fail");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("loginat")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_masteruser_name")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("user_masteruser_name");

                    b.ToTable("user_login_log");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.UserMaster.user_master", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.UserMaster.user_type_master", "user_type")
                        .WithMany()
                        .HasForeignKey("user_type_id1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user_type");
                });

            modelBuilder.Entity("TUSA.Domain.Entities.user_login_log", b =>
                {
                    b.HasOne("TUSA.Domain.Entities.UserMaster.user_master", "user_master")
                        .WithMany()
                        .HasForeignKey("user_masteruser_name")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("user_master");
                });
#pragma warning restore 612, 618
        }
    }
}
