//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUSA.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUSA.Service.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP admissions number..
        /// </summary>
        internal static string AdmissionsNo_IsInvalid {
            get {
                return ResourceManager.GetString("AdmissionsNo_IsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GON is already approved modifications are not accepted..
        /// </summary>
        internal static string GON_Already_Approved {
            get {
                return ResourceManager.GetString("GON_Already_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GON is already approved..
        /// </summary>
        internal static string GON_Already_Approved_ByOther {
            get {
                return ResourceManager.GetString("GON_Already_Approved_ByOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid GRN no or GRN is already approved..
        /// </summary>
        internal static string GRN_Already_Approved {
            get {
                return ResourceManager.GetString("GRN_Already_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid invoice line data..
        /// </summary>
        internal static string Invoice_Lineitem_Invalid {
            get {
                return ResourceManager.GetString("Invoice_Lineitem_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid item..
        /// </summary>
        internal static string Item_Invalid {
            get {
                return ResourceManager.GetString("Item_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid action step selected..
        /// </summary>
        internal static string Lab_Action_Step_Selected_Invalid {
            get {
                return ResourceManager.GetString("Lab_Action_Step_Selected_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid next action step..
        /// </summary>
        internal static string Lab_Next_ActionStep_Invalid {
            get {
                return ResourceManager.GetString("Lab_Next_ActionStep_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order..
        /// </summary>
        internal static string Order_Invalid {
            get {
                return ResourceManager.GetString("Order_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization&apos;s paid amount does not exceed the approved amount..
        /// </summary>
        internal static string PaidAmount_NotExceed_Approval {
            get {
                return ResourceManager.GetString("PaidAmount_NotExceed_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase request item {0} quantity is not the same as assigned..
        /// </summary>
        internal static string PO_Qty_NotEqual_Assinged {
            get {
                return ResourceManager.GetString("PO_Qty_NotEqual_Assinged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock not available..
        /// </summary>
        internal static string ProductStock_NotAvailable {
            get {
                return ResourceManager.GetString("ProductStock_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default rate chart is not available..
        /// </summary>
        internal static string RateChart_Default_Missing {
            get {
                return ResourceManager.GetString("RateChart_Default_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the test status, please refresh..
        /// </summary>
        internal static string Refresh_Test {
            get {
                return ResourceManager.GetString("Refresh_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or refresh token..
        /// </summary>
        internal static string RefreshToken_Invalid {
            get {
                return ResourceManager.GetString("RefreshToken_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        internal static string Request_Invalid {
            get {
                return ResourceManager.GetString("Request_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!, you can not edit this role..
        /// </summary>
        internal static string Role_NotEditable {
            get {
                return ResourceManager.GetString("Role_NotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self service is not allowed for sub-service..
        /// </summary>
        internal static string SelfService_NotAllowed {
            get {
                return ResourceManager.GetString("SelfService_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status has been modified by some other user..
        /// </summary>
        internal static string Status_Modifyed_ByOthers {
            get {
                return ResourceManager.GetString("Status_Modifyed_ByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor balance is updated by someone..
        /// </summary>
        internal static string VendorBalance_Mismatching {
            get {
                return ResourceManager.GetString("VendorBalance_Mismatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vendor payment amount is more than the due amount..
        /// </summary>
        internal static string VendorPay_MoreThanDue {
            get {
                return ResourceManager.GetString("VendorPay_MoreThanDue", resourceCulture);
            }
        }
    }
}
